image:
  tag: 15.0.2
service:
  type: NodePort
postgresql:
  enabled: false
extraEnv: |
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: admin
  - name: DB_VENDOR
    value: mysql
  - name: DB_ADDR
    value: "my-mysql"
  - name: DB_PORT
    value: "3306"
  - name: DB_USER
    value: keycloak
  - name: DB_PASSWORD
    value: keycloak
  - name: DB_DATABASE
    value: keycloak
  - name: JDBC_PARAMS
    value: useSSL=false