image:
  tag: 2.6.0-centos-oidc
env:
  database: postgres
  pg_host: my-postgres-postgresql
  pg_database: kong
  pg_user: kong
  pg_password: kong
  plugins: bundled,oidc
admin:
  enabled: true
  http:
    enabled: true