image:
  tag: 2.6.0
env:
  database: postgres
  pg_host: my-postgres-postgresql
  pg_database: kong
  pg_user: kong
  pg_password: kong
admin:
  enabled: true
  useTLS: false
readinessProbe:
  httpGet:
    scheme: HTTP
livenessProbe:
  httpGet:
    scheme: HTTP
ingressController:
  installCRDs: false