image:
  tag: 8.0.25-debian-10-r2
auth:
  rootPassword: root-password
  username: keycloak
  password: keycloak
  database: keycloak
primary:
  persistence:
    enabled: false
secondary:
  replicaCount: 0